//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPiBooks.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string Name { get; set; }
        public decimal Salary { get; set; }
        public decimal CIT_Percentage { get; set; }
        public decimal PF_Percentage { get; set; }
        public Nullable<decimal> NetSalary { get; set; }
        public string CitizenshipNumber { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<decimal> CreditBalance { get; set; }
        public Nullable<int> AvailableLeave { get; set; }
    }
}
